In [2]:
import numpy as np

In [6]:
np.logspace(0, 4.636624620543649, 32, base = 2)

array([ 1.        ,  1.10923769,  1.23040824,  1.36481519,  1.51390444,
        1.67927986,  1.8627205 ,  2.06619978,  2.29190666,  2.54226924,
        2.81998084,  3.12802902,  3.46972767,  3.84875269,  4.26918152,
        4.73553703,  5.25283613,  5.82664379,  6.46313287,  7.16915054,
        7.95229195,  8.82098191,  9.78456556, 10.85340885, 12.0390101 ,
       13.3541237 , 14.81289725, 16.43102386, 18.22591087, 20.21686718,
       22.42531095, 24.875     ])

In [5]:
np.log2((200 - 1) / (9 - 1))

4.636624620543649

In [9]:
np.array([(_ * ((np.sqrt(5) + 1) / 2)) % 1 for _ in range(1, 6 + 1)], dtype = np.float32)

array([0.618034  , 0.23606798, 0.85410196, 0.47213596, 0.09016994,
       0.7082039 ], dtype=float32)

In [10]:
np.random.randint(100)

18

In [26]:
X = np.array([1,2,3,4,5])

In [27]:
C = np.zeros(5, dtype = np.float32)

In [28]:
C

array([0., 0., 0., 0., 0.], dtype=float32)

In [29]:
C[:] = X

In [30]:
C

array([1., 2., 3., 4., 5.], dtype=float32)

In [31]:
9 // 2

4

In [33]:
print("9{123}")

9{123}


In [34]:
from itertools import combinations

In [36]:
np.array([_ for _ in combinations(np.arange(9), 3)], dtype = np.int32)

array([[0, 1, 2],
       [0, 1, 3],
       [0, 1, 4],
       [0, 1, 5],
       [0, 1, 6],
       [0, 1, 7],
       [0, 1, 8],
       [0, 2, 3],
       [0, 2, 4],
       [0, 2, 5],
       [0, 2, 6],
       [0, 2, 7],
       [0, 2, 8],
       [0, 3, 4],
       [0, 3, 5],
       [0, 3, 6],
       [0, 3, 7],
       [0, 3, 8],
       [0, 4, 5],
       [0, 4, 6],
       [0, 4, 7],
       [0, 4, 8],
       [0, 5, 6],
       [0, 5, 7],
       [0, 5, 8],
       [0, 6, 7],
       [0, 6, 8],
       [0, 7, 8],
       [1, 2, 3],
       [1, 2, 4],
       [1, 2, 5],
       [1, 2, 6],
       [1, 2, 7],
       [1, 2, 8],
       [1, 3, 4],
       [1, 3, 5],
       [1, 3, 6],
       [1, 3, 7],
       [1, 3, 8],
       [1, 4, 5],
       [1, 4, 6],
       [1, 4, 7],
       [1, 4, 8],
       [1, 5, 6],
       [1, 5, 7],
       [1, 5, 8],
       [1, 6, 7],
       [1, 6, 8],
       [1, 7, 8],
       [2, 3, 4],
       [2, 3, 5],
       [2, 3, 6],
       [2, 3, 7],
       [2, 3, 8],
       [2, 4, 5],
       [2,